trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          '$(Build.BuildId)'

- stage: Deploy
  displayName: Deploy to Kubernetes
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Kubernetes@1
      displayName: kubectl apply
      inputs:
        command: apply
        namespace: default
        useConfigurationFile: true
        configuration: '$(Build.SourcesDirectory)/k8s/deployment.yaml'
