apiVersion : apps/v1
kind: Deployment
metadata:
  name: nachobonillaweebhook 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nachobonillaweebhook
  template:
    metadata:
      labels:
        app: nachobonillaweebhook 
    spec:
      containers:
        - name: nachobonillaweebhook 
          image: containerweebhook.azurecr.io/nachobonillaweebhook
          ports:
          - containerPort: 8000