apiVersion: v1
kind: Service
metadata:
  name: nachobonillaweebhook
spec:
  type: LoadBalancer
  ports:
  - port: 80  # External port set to 80
    targetPort: 8000  # Target port on pods is 8000
  selector:
    app: nachobonillaweebhook