apiVersion: v1
kind: Service
metadata:
    name: nachobonillaweebhook
spec:
    type: LoadBalancer
    ports:
    port: 8080
    protocol: TCP
    targetPort: 8000
    
    selector:
        app: nachobonillaweebhook
